_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 53
                - 55
            "2":
                - 1
                - 11
                - 49
                - 53
                - 55
            "3":
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
                - 9
            "10":
                - 20
            "12": 0.19.9
            "13": darwin-x86_64
